name: jou
on: [push]

jobs:
  color:
    runs-on: ubuntu-latest
    steps:
      - name: display
        shell: pwsh
        run: |
          Write-Output " `e[31m Red text `e[0m "
          Write-Output "`e[BackgroundCode;TextColormYour Text`e[0m"


